version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: "database"
    ports:
        - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: myuser
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: todolist
    networks:
      - fullstack
#  go-todolist:
#    build: .
#    container_name: "go-todolist"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    networks:
#      - fullstack
volumes:
  mysql-data:
networks:
  fullstack:
    driver: bridge